# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebf83a13162a4db2742ad9d99c110d5ab9fd17fe81a4c8ffd8be7decc77b951bb4596eb613ce1c1ac23c6a509aca21a9060dbd839ebe3cbf84a74d3addb7e1a6

test:
  secret_key_base: 6b7831c3aed8f7a2f7147f7047f4c283db2ecc44c169b252da074645bdd2b5d15f15ce322ea976edbc01d49f90f48325bca4a1e87ac480e31175b224c67a9492

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
